# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160419002554 on 2016-04-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20160419_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_text',
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='todoapp.Tag'),
        ),
    ]
